### ISSUE TITLE
[1.12.2] Texture Hud oddity with the Debug Mode.

### ISSUE THREAD

**Issue by SonicX8000** [SekaiRed/AmbienceBlock#1]
Minecraft: 1.12.2
Forge: 14.23.5.2855

Mods: 3
AmbienceBlocks1.12.2-1.3.2
jei_1.12.2-4.16.1.302
ElenaiDodge2-1.12.2-1.0.9

=====

![ambblockguibug](https://user-images.githubusercontent.com/36653806/144836447-39491ffc-45f6-443a-bbec-97f4fcf698fa.png)

The Debug Mode if enabled causes the hud bar from Elenai Dodge 2 to recolor different colors. Also... the Hunger Bar becomes these weird blue things.

**Comment by SekaiRed** [comment]
It was something I forgot to write, I tested it with your mod setup and it seems to have fixed both the mod hud and the Minecraft hunger bar.

Sorry for the wait and thank you for reporting!
