### ISSUE TITLE
[Suggestion] Global sound

### ISSUE THREAD

**Issue by SteaSteaStea** [SekaiRed/AmbienceBlock#6]
Would it be possible to make the sounds play globally even when the blocks are out of render distance (but still chunk-loaded)?

**Comment by SekaiRed** [comment]
Sorry, it's currently only possible to have sounds playing when the client has the chunk loaded.

You can however use the [Ambience Compendium](https://github.com/SekaiRed/AmbienceBlock/wiki/Ambience-Compendium) to play sounds globally, you can also use a condition to set up a limit for where the sound should stop playing.
